### ISSUE TITLE
[Q] Is it really necessary to deploy the instance in a VPC?

### ISSUE THREAD

**Issue by angelbarrera92** [dalvarezquiroga/pacman-automatic-certbot-tf#1]
Hey, buddy!
Thanks for the repository, I have a little question. 
Is it really necessary to deploy the instance in a VPC? This adds complexity to the deployment when the target is very different.

**Comment by dalvarezquiroga** [comment]
Hi men! 
Not is necessary , deployed instance in VPC, but you can modifiy Terraform, as you wish ;-)
